// Display_Project, all rights reserved.

#pragma once

#include "CoreMinimal.h"
#include "DP_CoreEnums.h"
#include "DP_CoreStructures.h"

DECLARE_MULTICAST_DELEGATE_OneParam(FOnObjectTypeChangedSignature, EObjectType);
DECLARE_MULTICAST_DELEGATE_OneParam(FOnClickedObjectButtonSignature, EObjectType);
DECLARE_MULTICAST_DELEGATE_TwoParams(FOnAttributeChangedSignature, EAttributeType, FAttributeData);
DECLARE_MULTICAST_DELEGATE(FOnObjectSpawnSignature);
DECLARE_MULTICAST_DELEGATE(FOnObjectSpawnCompletedSignature);
DECLARE_MULTICAST_DELEGATE(FOnDestroyAllSignature);
DECLARE_MULTICAST_DELEGATE(FOnDestroySelectedSignature);
DECLARE_MULTICAST_DELEGATE(FOnWelcomeScreenCompletedSignature);
DECLARE_MULTICAST_DELEGATE_OneParam(FOnUpdatePreviewLocationSignature, AActor*);
DECLARE_MULTICAST_DELEGATE_OneParam(FOnObjectSelectedSignature, AActor*);
DECLARE_MULTICAST_DELEGATE(FOnFadeoutAnimationFinishedSignature);
DECLARE_MULTICAST_DELEGATE(FOnClickedSignature);
DECLARE_MULTICAST_DELEGATE(FOnQuitSignature);
DECLARE_MULTICAST_DELEGATE(FOnToggleScreenModeSignature);
DECLARE_MULTICAST_DELEGATE(FOnShowOptionsSignature);
DECLARE_MULTICAST_DELEGATE(FOnBackSignature);
DECLARE_MULTICAST_DELEGATE(FOnShowHelpSignature);
DECLARE_MULTICAST_DELEGATE_OneParam(FOnWarningResponseSignature, bool);
DECLARE_MULTICAST_DELEGATE(FOnInspectSignature);
DECLARE_MULTICAST_DELEGATE(FOnInspectCompletedSignature);
DECLARE_MULTICAST_DELEGATE_OneParam(FOnVideoQualityChangedSignature, EVideoQuality);
DECLARE_MULTICAST_DELEGATE_OneParam(FOnRotationSpeedChangedSignature, float);
DECLARE_MULTICAST_DELEGATE_OneParam(FOnSoundVolumeChangedSignature, float);
DECLARE_MULTICAST_DELEGATE(FOnShowSaveAndLoadSignature);
DECLARE_MULTICAST_DELEGATE_OneParam(FOnSaveSignature, const FText&);
DECLARE_MULTICAST_DELEGATE_OneParam(FOnLoadSignature, const FGuid&);
DECLARE_MULTICAST_DELEGATE_OneParam(FOnDeleteSaveSignature, const FGuid&);
DECLARE_MULTICAST_DELEGATE_OneParam(FOnSelectedSaveRecordSignature, const FGuid&);
DECLARE_MULTICAST_DELEGATE(FOnAssetsPreloadCompletedSignature);
